### PR TITLE
add game backend interractions

### PR DESCRIPTION
**Pull request by Eik-S**

### CODE REVIEW

**Comment by Eik-S** [comment]
@soerenreichardt could you have a look at the following bugs:
1. Neighbor checks on tile placements fail if both tiles have shared corners. (maybe also if just one has, couldn't reproduce yet). The backend responds with not matching but the touching sides match.
2. Resubscriptions during game work, but sometimes resubscribed users don't get events from the backend anymore.

**Comment by soerenreichardt** [comment]
The first bug should be resolved by #54, although I'm not entirely sure if that fix is always correct, i.e. do shared tile corners always match?

**Comment by Eik-S** [comment]
> The first bug should be resolved by #54, although I'm not entirely sure if that fix is always correct, i.e. do shared tile corners always match?

"they always match" maybe is a bit misleading. I would say that they match if the other fields on one side match as the logic behind a shared tile is "look at my neighbors"

**Comment by Eik-S** [comment]
On the other bug: It seems like only the first player is not getting any more events when reloading the browser. events are logged, so you can check this by taking a look into the web console.

**Pull request merged**
